// Copyright 2022 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "FlowExtensions.h"

#include "iree/compiler/Dialect/Flow/IR/FlowOps.h"
#include "iree/compiler/Dialect/Flow/Transforms/ConvertRegionToWorkgroups.h"
#include "iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.h"
#include "iree/compiler/Dialect/TensorExt/IR/TensorExtDialect.h"
#include "iree/compiler/Dialect/TensorExt/IR/TensorExtOps.h"
#include "llvm/ADT/DenseSet.h"
#include "mlir/Analysis/TopologicalSortUtils.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/Transforms/RegionUtils.h"

namespace mlir::iree_compiler {

IREE::transform_dialect::FlowExtensions::FlowExtensions() {
  // The transform interpreter only loads dialects that are declared as
  // generated by a loaded extension. `forall_to_flow` materializes ops in
  // these dialects, so without these declarations the rewrite crashes when
  // it tries to construct e.g. `iree_tensor_ext.dispatch.tensor`.
  declareGeneratedDialect<IREE::Flow::FlowDialect>();
  declareGeneratedDialect<IREE::TensorExt::IREETensorExtDialect>();
  declareGeneratedDialect<arith::ArithDialect>();
  declareGeneratedDialect<tensor::TensorDialect>();
  registerTransformOps<
#define GET_OP_LIST
#include "iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.cpp.inc"
      >();
}

void registerTransformDialectFlowExtension(DialectRegistry &registry) {
  registry.addExtensions<IREE::transform_dialect::FlowExtensions>();
}

// TODO: Upstream to ShapeType and reuse.
static SmallVector<int64_t> getIndicesOfDynamicDims(ShapedType t) {
  SmallVector<int64_t> res;
  for (int64_t dim = 0; dim != t.getRank(); ++dim) {
    if (t.isDynamicDim(dim)) {
      res.push_back(dim);
    }
  }
  return res;
}

//===---------------------------------------------------------------------===//
// Patterns for ForallOpToFlow rewrite.
//===---------------------------------------------------------------------===//

/// Populate the workgroup_count region of `dispatchOp`.
/// The workload operands are the normalized forall upper bounds.
/// Assumes the IREE::Flow::DispatchWorkgroupsOp is built with an empty region.
static LogicalResult populateWorkgroupCountComputingRegion(
    RewriterBase &rewriter, scf::ForallOp forallOp,
    IREE::Flow::DispatchWorkgroupsOp dispatchOp) {
  Location loc = forallOp.getLoc();
  OpBuilder::InsertionGuard g(rewriter);
  Region &r = dispatchOp.getWorkgroupCount();
  assert(r.empty() && "expected block-less workgroup_count region");
  SmallVector<Type> types(dispatchOp.getWorkload().size(),
                          rewriter.getIndexType());
  SmallVector<Location> locations(types.size(), loc);
  Block *block = rewriter.createBlock(&r, r.end(), types, locations);
  rewriter.setInsertionPointToStart(block);

  SmallVector<Value> results(block->getArguments());
  // Resize to `3` to match IREE's assumptions.
  for (unsigned i = results.size(); i < 3; ++i) {
    results.push_back(arith::ConstantIndexOp::create(rewriter, loc, 1));
  }
  IREE::Flow::ReturnOp::create(rewriter, loc, results);

  return success();
}

/// Rewrite ParallelInsertSlice ops in `InParallelOp` as Flow
/// DispatchTensorStoreOps.
/// Ops are inserted just before the `block` terminator.
static void rewriteParallelInsertSlices(RewriterBase &rewriter,
                                        scf::ForallOp forallOp,
                                        scf::InParallelOp InParallelOp,
                                        Block &block,
                                        ValueRange resultTensorOperands,
                                        ValueRange resultTensorsDynamicDims,
                                        IRMapping tensorToFlowBvm) {
  Location loc = InParallelOp.getLoc();
  for (const Operation &yieldingOp :
       llvm::make_early_inc_range(InParallelOp.getYieldingOps())) {
    auto parallelInsertOp = cast<tensor::ParallelInsertSliceOp>(&yieldingOp);
    OpBuilder::InsertionGuard g(rewriter);
    rewriter.setInsertionPoint(block.getTerminator());
    BlockArgument destBbArg = cast<BlockArgument>(parallelInsertOp.getDest());
    assert(destBbArg.getOwner()->getParentOp() == forallOp &&
           "expected that dest is an output bbArg");
    Value dest = forallOp.getTiedOpOperand(destBbArg)->get();
    auto resultIt = llvm::find(resultTensorOperands, dest);
    assert(resultIt != resultTensorOperands.end() &&
           "expected a recorded forall output");
    int64_t resultIndex = std::distance(resultTensorOperands.begin(), resultIt);
    auto dynamicDims = IREE::Util::findDynamicDimsInList(
        resultIndex, resultTensorOperands, resultTensorsDynamicDims);
    // clang-format off
    IREE::TensorExt::DispatchTensorStoreOp::create(rewriter,
        loc,
        parallelInsertOp.getSource(),
        tensorToFlowBvm.lookup(dest),
        dynamicDims,
        parallelInsertOp.getMixedOffsets(),
        parallelInsertOp.getMixedSizes(),
        parallelInsertOp.getMixedStrides());
    // clang-format on
    rewriter.eraseOp(parallelInsertOp);
  }
}

/// Rewrite ExtractSlice ops in `dispatchOp` as
/// IREE::TensorExt::DispatchTensorLoadOps. Takes a list of all tensor and all
/// tensorDynamicDims operands to the dispatchOp as well as a IRMapping from
/// tensor operands to the corresponding Flow dispatch tensor bbArgs.
static void rewriteExtractSlices(RewriterBase &rewriter, scf::ForallOp forallOp,
                                 IREE::Flow::DispatchWorkgroupsOp dispatchOp,
                                 ValueRange tensorOperands,
                                 ValueRange tensorDynamicDims,
                                 IRMapping tensorToFlowBvm) {
  dispatchOp->walk([&](tensor::ExtractSliceOp extractSliceOp) {
    Value source = extractSliceOp.getSource();
    if (auto sourceBbArg = dyn_cast<BlockArgument>(source)) {
      if (sourceBbArg.getOwner()->getParentOp() == forallOp.getOperation()) {
        source = forallOp.getTiedOpOperand(sourceBbArg)->get();
      }
    }

    auto it = llvm::find(tensorOperands, source);
    if (it == tensorOperands.end()) {
      return;
    }
    int64_t index = std::distance(tensorOperands.begin(), it);
    Value sourceFlow = tensorToFlowBvm.lookupOrNull(source);
    if (!sourceFlow) {
      return;
    }

    Location loc = extractSliceOp.getLoc();
    OpBuilder::InsertionGuard g(rewriter);
    rewriter.setInsertionPoint(extractSliceOp);
    auto dynamicDims = IREE::Util::findDynamicDimsInList(index, tensorOperands,
                                                         tensorDynamicDims);
    // clang-format off
    Value load = IREE::TensorExt::DispatchTensorLoadOp::create(rewriter,
        loc,
        extractSliceOp.getType(),
        sourceFlow,
        dynamicDims,
        extractSliceOp.getMixedOffsets(),
        extractSliceOp.getMixedSizes(),
        extractSliceOp.getMixedStrides());
    // clang-format on
    rewriter.replaceOp(extractSliceOp, load);
  });
}

static void cloneOpsIntoForallOp(RewriterBase &rewriter, scf::ForallOp forallOp,
                                 bool cloneTensorCompute) {
  // 1. Find all ops that should be cloned into the ForallOp.
  llvm::SetVector<Value> valuesDefinedAbove;
  mlir::getUsedValuesDefinedAbove(forallOp.getRegion(), valuesDefinedAbove);
  // Add all ops who's results are used inside the ForallOp to the
  // worklist.
  llvm::SetVector<Operation *> worklist;
  for (Value v : valuesDefinedAbove) {
    if (Operation *op = v.getDefiningOp()) {
      worklist.insert(op);
    }
  }
  llvm::SmallVector<Operation *> opsToClone;
  llvm::DenseSet<Operation *> visited;

  // Process all ops in the worklist.
  while (!worklist.empty()) {
    Operation *op = worklist.pop_back_val();
    if (visited.contains(op)) {
      continue;
    }
    visited.insert(op);

    // Do not clone ops that are not cloneable.
    if (!IREE::Flow::isCloneableIntoDispatchOp(op)) {
      continue;
    }

    // A transform schedule may already have selected and fused all numerical
    // computation. In that case, capture remaining tensor producers instead of
    // adding unscheduled work to the dispatch. Keep boundary slices, empty
    // destinations and constants available without materializing new buffers.
    if (!cloneTensorCompute &&
        llvm::any_of(op->getResultTypes(),
                     [](Type type) { return isa<TensorType>(type); }) &&
        !isa<tensor::ExtractSliceOp, tensor::EmptyOp, arith::ConstantOp>(op)) {
      continue;
    }

    // Do not clone ParallelInsertSliceOp destinations.
    bool isDestination = any_of(
        forallOp.getTerminator().getYieldingOps(), [&](Operation &insertOp) {
          return cast<tensor::ParallelInsertSliceOp>(&insertOp)
                     .getDest()
                     .getDefiningOp() == op;
        });
    if (isDestination) {
      continue;
    }

    opsToClone.push_back(op);

    // Add all operands to the worklist.
    for (Value operand : op->getOperands()) {
      Operation *operandOp = operand.getDefiningOp();
      if (!operandOp) {
        continue;
      }
      worklist.insert(operandOp);
    }
  }

  // 2. Clone dependencies before their users. Reversing the discovery order
  // alone is insufficient when multiple captured producers share a dependency.
  // Remap operands of later clones as well as uses already in the forall body.
  bool sorted = mlir::computeTopologicalSorting(opsToClone);
  (void)sorted;
  assert(sorted && "could not compute topological sorting");
  IRMapping mapping;
  OpBuilder::InsertionGuard g(rewriter);
  rewriter.setInsertionPointToStart(&forallOp.getRegion().getBlocks().front());
  for (Operation *op : opsToClone) {
    Operation *cloned = rewriter.clone(*op, mapping);
    SmallVector<OpOperand *> uses;
    for (OpOperand &use : op->getUses()) {
      if (forallOp->isProperAncestor(use.getOwner())) {
        uses.push_back(&use);
      }
    }
    for (OpOperand *use : uses) {
      unsigned resultNum = cast<OpResult>(use->get()).getResultNumber();
      rewriter.modifyOpInPlace(
          use->getOwner(), [&]() { use->set(cloned->getOpResult(resultNum)); });
    }
  }
}

/// Rewrite a ForallOp into a IREE::Flow::DispatchWorkGroupsOp.
/// This rewrite proceeds in a few steps:
///   - Step 0: Clone certain ops into the ForallOp (as per IREE
///     heuristic), so that they are part of the dispatch region.
///   - Step 1: Compute the result types and their result dynamic dim operands.
///     Use shared output order regardless of the order of parallel stores.
///   - Step 2: Get values defined above and separate them between non-tensors,
///     tensors and introduce appropriate tensor dims.
///   - Step 3: Create ordered vectors of operands to pass to the builder and
///     build the dispatchOp.
///   - Step 4: Populate the workgroupCount region of the dispatchOp and set
///     the workload operands to the values defined above.
///   - Step 5: Fixup dispatchOp bbArgs and terminator.
///   - Step 6: Move the body of forallOp to the dispatchOp.
///   - Step 7: Set up bvm for RAUWIf. In particular, tensor operands become
///     flow dispatch tensor bbArgs and need to be
///     iree_tensor_ext.dispatch.tensor.load'ed.
///   - Step 8: Plug dispatch workgroup id and count values into the bvm.
///   - Step 9. Rewrite tensor::ExtractSlice and ParallelInsert ops to the
///     relevant Flow DispatchTensorLoad/Store version.
///   - Step 10: Perform RAUWIf.
///   - Step 11: Drop the terminator and replace forallOp.
// TODO: n-D ForallOp
FailureOr<IREE::Flow::DispatchWorkgroupsOp>
rewriteForeachThreadToFlowDispatchWorkgroups(scf::ForallOp forallOp,
                                             RewriterBase &rewriter,
                                             bool cloneTensorCompute) {
  // Check the supported domain before cloning or replacing any computation.
  if (!forallOp.isNormalized() || forallOp.getRank() == 0 ||
      forallOp.getRank() > 3) {
    return forallOp.emitOpError(
        "expected a normalized forall with one to three dimensions");
  }
  llvm::SmallDenseSet<Value> destinations;
  for (Value output : forallOp.getOutputs()) {
    if (!destinations.insert(output).second) {
      return forallOp.emitOpError("expected distinct shared output operands");
    }
  }
  if (llvm::any_of(forallOp.getTerminator().getYieldingOps(),
                   [](Operation &op) {
                     return !isa<tensor::ParallelInsertSliceOp>(op);
                   })) {
    return forallOp.emitOpError("expected parallel_insert_slice yields");
  }

  // Step 0: Clone ops into the ForallOp.
  cloneOpsIntoForallOp(rewriter, forallOp, cloneTensorCompute);

  OpBuilder::InsertionGuard g(rewriter);
  rewriter.setInsertionPoint(forallOp);

  // Entry point start just before the forallOp.
  Location loc = forallOp.getLoc();
  scf::InParallelOp InParallelOp = forallOp.getTerminator();

  // Step 1: Compute all dynamic result dims.
  // Shared outputs, result types, dimensions, and ties must have the same
  // order. The parallel_insert_slice operations are unordered and fusion can
  // insert their stores in a different order from the forall results.
  llvm::SetVector<Value> resultTensorOperands;
  SmallVector<Value> resultTensorsDynamicDims;
  for (Value dest : forallOp.getOutputs()) {
    resultTensorOperands.insert(dest);
    auto dynamicDims =
        getIndicesOfDynamicDims(cast<ShapedType>(dest.getType()));
    for (int64_t dim : dynamicDims) {
      resultTensorsDynamicDims.push_back(
          tensor::DimOp::create(rewriter, loc, dest, dim));
    }
  }
  assert(resultTensorOperands.size() == forallOp.getNumResults() &&
         "Expected as many resultTensorOperands as results of forallOp");

  // Step 2. Get values defined above and separate them between non-tensors,
  // tensors and introduce appropriate tensor dims.
  // Tensors that have already been recorded as resultTensorOperands are
  // omitted to avoid duplications.
  llvm::SetVector<Value> valuesDefinedAbove;
  mlir::getUsedValuesDefinedAbove(forallOp.getRegion(), valuesDefinedAbove);

  SmallVector<Value> nonTensorOperands, tensorOperands, tensorDynamicDims;
  for (Value v : valuesDefinedAbove) {
    auto tensorType = dyn_cast<RankedTensorType>(v.getType());
    if (!tensorType) {
      nonTensorOperands.push_back(v);
      continue;
    }
    if (resultTensorOperands.contains(v)) {
      continue;
    }
    tensorOperands.push_back(v);
    for (int64_t dim : getIndicesOfDynamicDims(tensorType)) {
      tensorDynamicDims.push_back(tensor::DimOp::create(rewriter, loc, v, dim));
    }
  }
  // Also add shared outputs. (These are usually already added as result
  // tensor operands.)
  for (Value v : forallOp.getOutputs()) {
    auto tensorType = cast<RankedTensorType>(v.getType());
    if (resultTensorOperands.contains(v)) {
      continue;
    }
    tensorOperands.push_back(v);
    for (int64_t dim : getIndicesOfDynamicDims(tensorType)) {
      tensorDynamicDims.push_back(tensor::DimOp::create(rewriter, loc, v, dim));
    }
  }

  // Step 3. Create ordered vectors of operands to pass to the builder and
  // build the dispatchOp. Its workload carries the normalized iteration counts;
  // its count region is populated next.
  SmallVector<Value> nonDimOperands;
  llvm::append_range(nonDimOperands, nonTensorOperands);
  llvm::append_range(nonDimOperands, tensorOperands);
  // A tensor.empty init carries shape, not existing storage that the dispatch
  // must update. Give these results independent, untied output bindings. Tying
  // them to captured empty tensors lets later CSE merge two destinations and
  // incorrectly force distinct results to share a buffer.
  SmallVector<int64_t> tiedOperands;
  SmallVector<Value> operandDynamicDims = tensorDynamicDims;
  [[maybe_unused]] unsigned untiedResults = 0;
  for (auto [index, output] : llvm::enumerate(resultTensorOperands)) {
    if (output.getDefiningOp<tensor::EmptyOp>()) {
      tiedOperands.push_back(IREE::Util::TiedOpInterface::kUntiedIndex);
      ++untiedResults;
      continue;
    }
    tiedOperands.push_back(nonDimOperands.size());
    nonDimOperands.push_back(output);
    llvm::append_range(operandDynamicDims,
                       IREE::Util::findDynamicDimsInList(
                           index, resultTensorOperands.getArrayRef(),
                           resultTensorsDynamicDims));
  }
  int64_t sizeNonTensors = nonTensorOperands.size();
  int64_t sizeNonResultTensors = tensorOperands.size();
  // Separate out tensorOperands and tensorDynamicDims for RAUWIf purposes.
  SmallVector<Value> allTensorOperands = tensorOperands;
  llvm::append_range(allTensorOperands, resultTensorOperands);
  SmallVector<Value> allTensorDynamicDims = tensorDynamicDims;
  llvm::append_range(allTensorDynamicDims, resultTensorsDynamicDims);
  // Dynamic tensor dimensions are both shape metadata and explicit captures.
  // The builder creates exactly one body argument per captured operand.
  SmallVector<Value> allOperands = nonDimOperands;
  llvm::append_range(allOperands, allTensorDynamicDims);
  // clang-format off
  auto dispatchOp = IREE::Flow::DispatchWorkgroupsOp::create(rewriter,
      loc,
      /*workload=*/forallOp.getUpperBound(rewriter),
      /*resultTypes=*/forallOp.getResultTypes(),
      /*resultDims=*/resultTensorsDynamicDims,
      /*operands=*/allOperands,
      /*operandDims=*/operandDynamicDims,
      /*tiedOperands=*/tiedOperands);
  // clang-format on

  // Step 4. Outline the compute workload region and set up the workload
  // operands.
  if (failed(populateWorkgroupCountComputingRegion(rewriter, forallOp,
                                                   dispatchOp))) {
    return forallOp->emitOpError(
               "failed to populate workload region for dispatchOp: ")
           << dispatchOp;
  }

  // Step 5. The builder supplied operand arguments in the same order as
  // allOperands, followed by independent output arguments. Add the terminator.
  Region &region = dispatchOp.getWorkgroupBody();
  Block *block = &region.front();
  {
    OpBuilder::InsertionGuard g(rewriter);
    rewriter.setInsertionPointToEnd(block);
    IREE::Flow::ReturnOp::create(rewriter, loc);
  }
  assert(block->getNumArguments() == allOperands.size() + untiedResults &&
         "Expected operand arguments and independent output arguments");

  // Step 6. Move the body of forallOp to the dispatchOp.
  block->getOperations().splice(block->begin(),
                                forallOp.getRegion().front().getOperations());

  // Step 7. Set up bvm for RAUWIf.
  // Generally, allOperands map to their corresponding bbArg but there is a
  // twist: tensor operands map to iree_tensor_ext.dispatch.tensor bbArgs and we
  // need to insert an explicit IREE::TensorExt::DispatchTensorLoadOp to get
  // back a proper tensor. Save the tensor operand -> flow tensor bbArg mapping
  // in `tensorToFlowBvm`.
  IRMapping bvm, tensorToFlowBvm;
  auto flowBbArgs =
      block->getArguments().slice(sizeNonTensors, sizeNonResultTensors);
  tensorToFlowBvm.map(tensorOperands, flowBbArgs);
  for (auto [index, output] : llvm::enumerate(resultTensorOperands)) {
    tensorToFlowBvm.map(output, dispatchOp.getOutputBlockArgument(index));
  }
  bvm.map(allOperands, block->getArguments().take_front(allOperands.size()));
  auto allTensorDimsBBArgs = block->getArguments().slice(
      nonDimOperands.size(), allTensorDynamicDims.size());
  for (auto en : llvm::enumerate(allTensorOperands)) {
    OpBuilder::InsertionGuard g(rewriter);
    rewriter.setInsertionPointToStart(block);
    // Warning: findDynamicDimsInList needs to use the RankedTensorTypes and
    // does not work out of the box with IREE::TensorExt::DispatchTensorType.
    auto dynamicDims = IREE::Util::findDynamicDimsInList(
        en.index(), allTensorOperands, allTensorDimsBBArgs);
    auto loadOp = IREE::TensorExt::DispatchTensorLoadOp::create(
        rewriter, loc, cast<RankedTensorType>(en.value().getType()),
        tensorToFlowBvm.lookup(en.value()), dynamicDims);
    // Replace the tensor -> iree_tensor_ext.dispatch.tensor entry by a
    // tensor -> iree_tensor_ext.dispatch.tensor.load entry.
    bvm.map(en.value(), loadOp.getResult());
  }
  // Shared output block arguments can also be used by tensor.dim and other
  // tensor operations, not only extract_slice. They must be remapped before
  // the old forall block is erased. Map them to their output binding's tensor
  // view; this introduces no buffer copy.
  for (auto [output, argument] :
       llvm::zip_equal(forallOp.getOutputs(), forallOp.getRegionOutArgs())) {
    bvm.map(argument, bvm.lookup(output));
  }

  // Step 8. Plug dispatch workgroup id and count values into the bvm.
  rewriter.setInsertionPointToStart(block);
  SmallVector<Value, 8> workgroupIds, workgroupCounts;
  for (int64_t rank :
       llvm::seq<int64_t>(0, forallOp.getInductionVars().size())) {
    workgroupIds.push_back(
        IREE::Flow::DispatchWorkgroupIDOp::create(rewriter, loc, rank));
    workgroupCounts.push_back(
        IREE::Flow::DispatchWorkgroupCountOp::create(rewriter, loc, rank));
  }
  bvm.map(forallOp.getInductionVars(), workgroupIds);
  bvm.map(forallOp.getUpperBound(rewriter), workgroupCounts);

  // Step 9. Rewrite tensor::ExtractSlice and ParallelInsert ops to the
  // relevant Flow DispatchTensorLoad/Store version.
  rewriteParallelInsertSlices(rewriter, forallOp, InParallelOp, *block,
                              resultTensorOperands.getArrayRef(),
                              resultTensorsDynamicDims, tensorToFlowBvm);
  rewriteExtractSlices(rewriter, forallOp, dispatchOp, allTensorOperands,
                       allTensorDynamicDims, tensorToFlowBvm);

  // Step 10. Perform RAUWIf.
  for (auto mapEntry : bvm.getValueMap()) {
    assert(mapEntry.first.getType() == mapEntry.second.getType() &&
           "must have the same type");
    mapEntry.first.replaceUsesWithIf(mapEntry.second, [&](OpOperand &use) {
      return dispatchOp->isProperAncestor(use.getOwner());
    });
  }

  // Step 11. Drop the terminator and replace forallOp.
  rewriter.eraseOp(InParallelOp);
  rewriter.replaceOp(forallOp, dispatchOp.getResults());

  return dispatchOp;
}

//===---------------------------------------------------------------------===//
// IREE-specific transformations defined outside of iree_linalg_transform.
//===---------------------------------------------------------------------===//

DiagnosedSilenceableFailure
IREE::transform_dialect::ForeachThreadToFlowDispatchWorkgroupsOp::applyToOne(
    transform::TransformRewriter &rewriter, scf::ForallOp target,
    transform::ApplyToEachResultList &results, transform::TransformState &) {
  IRRewriter patternRewriter(target->getContext());
  FailureOr<IREE::Flow::DispatchWorkgroupsOp> result =
      rewriteForeachThreadToFlowDispatchWorkgroups(target, patternRewriter,
                                                   getCloneTensorCompute());
  if (failed(result)) {
    return emitDefaultDefiniteFailure(target);
  }
  results.push_back(*result);
  return DiagnosedSilenceableFailure::success();
}

void IREE::transform_dialect::ForeachThreadToFlowDispatchWorkgroupsOp::
    getEffects(SmallVectorImpl<MemoryEffects::EffectInstance> &effects) {
  transform::consumesHandle(getTargetMutable(), effects);
  transform::producesHandle(getOperation()->getOpResults(), effects);
  transform::modifiesPayload(effects);
}

DiagnosedSilenceableFailure
IREE::transform_dialect::RegionToWorkgroupsOp::applyToOne(
    transform::TransformRewriter &rewriter, IREE::Flow::DispatchRegionOp target,
    transform::ApplyToEachResultList &results, transform::TransformState &) {
  FailureOr<IREE::Flow::DispatchWorkgroupsOp> result =
      rewriteFlowDispatchRegionToFlowDispatchWorkgroups(target, rewriter);
  if (failed(result)) {
    return emitDefaultDefiniteFailure(target);
  }
  results.push_back(*result);
  return DiagnosedSilenceableFailure::success();
}

void IREE::transform_dialect::RegionToWorkgroupsOp::getEffects(
    SmallVectorImpl<MemoryEffects::EffectInstance> &effects) {
  transform::consumesHandle(getTargetMutable(), effects);
  transform::producesHandle(getOperation()->getOpResults(), effects);
  transform::modifiesPayload(effects);
}

} // namespace mlir::iree_compiler

#define GET_OP_CLASSES
#include "iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.cpp.inc"
